spring.application.name=proposal

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db-proposal
spring.datasource.username=postgres
spring.datasource.password=nova_senha

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Application port
server.port=8080

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.main.allow-bean-definition-overriding=true

# Rabbit MQ Configuration
broker.queue.proposal.status=queue.status
spring.rabbitmq.host=possum.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=gycjyrio
spring.rabbitmq.password=OvdEeIOwS_gDzL6ISWziakIEebjY6_az
spring.rabbitmq.virtual-host=gycjyrio
spring.rabbitmq.ssl.enabled=true